### PR TITLE
Group: subclass Mapping for dict-like behaviour

### PR DESCRIPTION
**Pull request by clbarnes**
Started working on some other stuff but you've been busy today and made it obsolete :P 

This is pretty much all that remains. By inheriting from `Mapping` and implementing the `__len__`, `__iter__` and `__getitem__`, we get `__contains__`, `get`, `keys`, `values`, and `items` for free in a `dict`-compatible way.

### CODE REVIEW

**Comment by constantinpape** [comment]
Yeah, I ran into some more or less related issues and while fixing them started the whole 1.0 effort.

I don't get one of the changes (review is on the way).
Otherwise, this looks good. 
I will fix the tests on the release branch later and then we can merge this.

**Comment by constantinpape** [comment]
Oh, I misread something. Looks all fine.
I will merge once I fixed the tests.

**Comment by constantinpape** [comment]
Sorry, took me a while to look into the errors.
The tests should pass now, and it doesn't look like you broke any additional ones, so this is good to merge.

**Comment by clbarnes** [comment]
Great, thanks!

Even if it's too early for the 1.0 release, a 0.9 release with an implementation of #39 on the C++ side would be pretty helpful for me.

**Pull request merged**
