### PR TITLE
Add Python 3.10 to CI builds

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by constantinpape** [comment]
Indeed, looks like some dependency conflict due to the version pinning.
We can try to loosen the pins and see if this fixes the conflicts and if builds are still passing.

**Comment by DimitriPapadopoulos** [comment]
I could be a problem of dependencies:

**Ensuring environment...**
```
[...]
  Making patched copy of 'environment-file: .github/workflows/environment.yaml'
  Using: /home/runner/work/z5/z5/.github/workflows/setup-miniconda-patched-environment.yaml
  name: z5-build-env
  channels:
    - conda-forge
  dependencies:
    - cmake
    - compilers
    - bzip2
    - lz4-c
    - xz
    - zlib
    - boost-cpp>=1.63
    - 'xtensor>=0.21,<0.22'
    - 'xtensor-python>=0.24,<0.25'
    - 'xsimd >=7,<8'
    - blosc
    - imageio
    - nlohmann_json
    - zarr
    - h5py
    - python=3.10
```
But then I cannot make any sense of the description of the conflicts. Conflicts are everywhere and it is not easy to pinpoint the root cause (I would bet on `'xtensor>=0.21,<0.22'` / `'xtensor-python>=0.24,<0.25'` but that's only a gut feeling).

**Comment by DimitriPapadopoulos** [comment]
Fixed CI by removing version pinning here:
https://github.com/constantinpape/z5/blob/f3f1eb13a3134d0b6b98e89c24e7e8ad77538c3c/conda-recipe/meta.yaml#L26-L27
and here:
https://github.com/constantinpape/z5/blob/f3f1eb13a3134d0b6b98e89c24e7e8ad77538c3c/.github/workflows/environment.yaml#L12-L14

I don't know why version pinning is required here and how you find the proper version to use.

**Comment by constantinpape** [comment]
Thanks for looking into this!

> I don't know why version pinning is required and how you find the proper version to use.

The version pins are required because the xtensor projects have a fairly unstable API, so just installing the latest version is a bit dangerous.
For the correct version pins you can take the ones from conda-forge: https://github.com/conda-forge/z5py-feedstock/blob/main/recipe/meta.yaml#L27-L29. They should work for python 3.10.

(Sorry that I realized this only now; just recalled that I had the same issues for the python 3.10 build on conda-forge half a year ago or so.)

**Comment by DimitriPapadopoulos** [comment]
I have updated [**`.github/workflows/environment.yaml`**](https://github.com/constantinpape/z5/blob/master/.github/workflows/environment.yaml) accordingly.

I don't know what to do with [**`conda-recipe/meta.yaml`**](https://github.com/constantinpape/z5/blob/master/conda-recipe/meta.yaml):
https://github.com/constantinpape/z5/blob/f3f1eb13a3134d0b6b98e89c24e7e8ad77538c3c/conda-recipe/meta.yaml#L26-L27

**Review by constantinpape — APPROVED** [review]
Thanks!
(And the changes in the conda-recipe are fine; this one is deprecated and just left here for reference.)

**Pull request merged**
