### PR TITLE
Environment files

### LINKED ISSUE #91: Build against python 3.7
Travis needs to use the `xenial` image to for this.

### PR DESCRIPTION
**Pull request by clbarnes**
There are now conda environment files for each supported python version on unix, which travis uses to make the build environment.

All of the environment variables are set from a single script, which travis also uses.

With these changes, I have built `z5py` locally for the first time since I started contributing to it 8 months ago :laughing: 

Also resolves #91

Remaining issues:

1. All of the py3 environment files are basically the same, except for the name (which is overridden by travis anyway) and the python version (which is known when you need them anyway, by definition). However, environment files don't compose nicely in the way that `requirements.txt` do so I don't think there's a better way of doing it. We could reduce duplication by having one py2 and py3 file and then manually reinstalled python for the different minor versions. We could possibly reduce it down to one and manually install `futures` for py2, but I think installing py2 in a py3 conda environment would be slow as it would need to reinstall a bunch of dependent packages.
2. I don't know how appveyor or indeed windows works so this is just for linux/travis right now.
3. I think the gitignore doesn't cover all the build files, and the `clean` recipe in the cmake-generated Makefile doesn't remove them

### CODE REVIEW

**Comment by constantinpape** [comment]
> With these changes, I have built `z5py` locally for the first time since I started contributing to it 8 months ago laughing

Nice :). (And yes, the cmake builds can be pretty tricky).

In general, this looks really good, just addressing the issues you mentioned:
1. Unifying at least the python 3 versions would be nice. I also don't know if there is a good way to do this. Maybe someone more conda savvy would have an idea. Any ideas @jakirkham?
2. The environment files could also be used in appveyor, but you don't need to worry about this right now. The appveyor build is broken due to some xtensor issues I haven't gotten around to figure out yet...
3. What isn't covered by the gitignore? I didn't spend time on properly setting up the `clean` command, so it is very likely that this does not do a proper job. Feel free to make an issue about that, I will try to look into this at some point.

**Comment by constantinpape** [comment]
> As for 1, you can update environments from environment files, but it would make it more awkward for the caller.

Sure, but this would mean reinstalling all packages that were build for the specific python version.
I would rather have something like `conda env create -f env.yaml --python 3.6`. If this is not possible, we can leave it as is.



> For 2: The only thing I thought might be an issue with using the environment files for windows is that they now include cmake and GCC, so that they truly encapsulate a reproducible build environment (I was having GCC issues when I tried to build locally before).

Ok, I see. Then we would need windows envs without the GCC and CMake dependencies. I will keep that in mind when fixing the win appveyor build.

> For 3, I ended up with a load of extra CMakeLists, CMakeCache files and similar strewn around but I didn't `mkdir bld && cd bld` first, so that might be why.

Yes that explains it.

> In fairness my conda setup is unusual because I'm using pyenv, which didn't work with conda >4.3 until a couple of days ago and still requires some workarounds.

That probably explains some of your build issues. In the cmake files, I try to automagically set the `CMAKE_PREFIX_PATH` to the active conda env and maybe this fails with pyenv.
You can always set the prefix path yourself by passing `-DCMAKE_PREFIX_PATH=/path/to/env` to `cmake`. I will add this to the README.

**Comment by clbarnes** [comment]
There's nothing else I'd want to change right now, but maybe we should leave an issue open for reducing duplication between the environment files as documentation/ in case anyone has any better ideas/ in case something becomes available in the future!

**Comment by constantinpape** [comment]
Ok, thanks for the contribution!
Opening an issue on the duplication issue is a good idea.
Can you do that?

**Comment by constantinpape** [comment]
@clbarnes the latest release is on conda-forge already, checkout https://anaconda.org/conda-forge/z5py.

**Comment by constantinpape** [comment]
Ok, it looks like the new linux versions were only built for the gcc7 label.

```
cpape@cpape-UX490UA:~$ conda search -c conda-forge z5py
Loading channels: done
# Name                  Version           Build  Channel             
z5py                      1.0.0  py27hf823e65_0  conda-forge         
z5py                      1.0.0  py27hf823e65_1  conda-forge         
z5py                      1.0.0  py35hf823e65_0  conda-forge         
z5py                      1.0.0  py35hf823e65_1  conda-forge         
z5py                      1.0.0  py36hf823e65_0  conda-forge         
z5py                      1.0.0  py36hf823e65_1  conda-forge         
z5py                      1.1.0  py27hf823e65_0  conda-forge         
z5py                      1.1.0  py36hf823e65_0  conda-forge         
cpape@cpape-UX490UA:~$ conda search -c conda-forge/label/gcc7 z5py
Loading channels: done
# Name                  Version           Build  Channel             
z5py                      1.1.1 py27h9082789_1000  conda-forge/label/gcc7
z5py                      1.1.1 py36h9082789_1000  conda-forge/label/gcc7
z5py                      1.1.1 py37h9082789_1000  conda-forge/label/gcc7
z5py                      1.2.0 py27h9082789_1000  conda-forge/label/gcc7
z5py                      1.2.0 py36h9082789_1000  conda-forge/label/gcc7
z5py                      1.2.0 py37h9082789_1000  conda-forge/label/gcc7
z5py                      1.3.0 py27h9082789_1000  conda-forge/label/gcc7
z5py                      1.3.0 py36h9082789_1000  conda-forge/label/gcc7
z5py                      1.3.0 py37h9082789_1000  conda-forge/label/gcc7
```

**Pull request merged**
